name: "Job 7 — Nuclei Scan"

on:
  workflow_call:
    inputs:
      target_url:
        required: true
        type: string

jobs:
  nuclei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Nuclei Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: ${{ inputs.target_url }}
          args: "-severity critical,high"

      - name: Upload Nuclei Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-report
          path: nuclei-report.txt
